### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by micahbf** [Data-Liberation-Front/csvlint.rb#244]
### Expected Behaviour

Hello! I just spent some time tracking down why Csvlint (used as a gem) was always incorrectly reporting an encoding error when there was none.

I see that this was actually an issue with Ruby 2.5+ which was fixed in #217 , however a release (0.4.0) has not been cut since 2017, so this fix (and, I would assume, other fixes) is not available.

Would it be possible to release a new version so we can take advantage of all the improvements since 2017?

### Desired Behaviour (for improvement suggestions only)
Release new version

### Current Behaviour (for problems)
Encounter bug that has since been fixed on master

### Your Environment
Ruby 2.5.7
csvlint 0.4.0

**Comment by Floppy** [comment]
new version out now, and supports Ruby up to 3.1! Sorry it took SO LONG. :)
