### ISSUE TITLE
Requires ruby < 3.2

### ISSUE THREAD

**Issue by woodhull** [Data-Liberation-Front/csvlint.rb#272]
The latest version of the code enforces a ruby version < 3.2.0.

Is this intentional? https://github.com/Data-Liberation-Front/csvlint.rb/blob/main/csvlint.gemspec#L19

It causes the gem version for modern applications to resolve to an old version of the gem that does not have this constraint specified.

**Comment by Floppy** [comment]
We've had issues with minor patch versions before, so it's just a safety thing. I didn't clock that Ruby 3.2 got released on xmas day (thanks, Ruby!) so I'll add it to the test suite and check it works, then change the requirement. Thanks for letting me know!

**Comment by Floppy** [comment]
v1.1.0 now released with Ruby 3.2 support. Enjoy :)
